// Turns the .archive/projects.json snapshot into seed SQL for D1.
//
// Emits SQL rather than inserting through Drizzle because it runs on plain
// Node, outside a Worker, where there is no D1 binding to hand the ORM. The
// output is applied with `wrangler d1 execute --file`, against local or remote.
//
// This is the migration's data-shaping step, deliberately separate from the R2
// image copy: media_key is left NULL here and filled in by the media PR once
// the images exist in R2.
//
// Kept out of migrations/ deliberately: `wrangler d1 migrations apply` runs
// every .sql in that directory, and this file opens with DELETE statements.
//
// Usage: node scripts/build-seed.mjs > seeds/seed.sql   (or `pnpm db:seed`)

import { readFileSync } from "node:fs"

const projects = JSON.parse(
  readFileSync(new URL("../.archive/projects.json", import.meta.url), "utf8"),
)

// Derived github.com/shayyz-code/<slug> URLs, checked with an authenticated
// `gh repo view`. Only public repos that actually resolve get a repo_url — a
// private repo 404s for visitors, which is worse than showing no link.
const PUBLIC_REPOS = new Set(["pali-canon-ai", "rangoon-academy", "poolang"])

const q = (v) =>
  v === null || v === undefined || v === ""
    ? "NULL"
    : `'${String(v).replace(/'/g, "''")}'`

const lines = [
  "-- Generated by scripts/build-seed.mjs from .archive/projects.json.",
  "-- Do not hand-edit; regenerate instead.",
  "",
  "DELETE FROM project_tags;",
  "DELETE FROM tags;",
  "DELETE FROM projects;",
  "",
]

// Collect tags in first-seen order so ids are stable across regenerations.
const tagOrder = []
for (const p of projects) {
  for (const t of String(p.tags ?? "").split(", ")) {
    const tag = t.trim()
    if (tag && !tagOrder.includes(tag)) tagOrder.push(tag)
  }
}
for (const name of tagOrder) {
  lines.push(`INSERT INTO tags (name) VALUES (${q(name)});`)
}
lines.push("")

projects.forEach((p, i) => {
  const repoUrl = PUBLIC_REPOS.has(p.slug)
    ? `https://github.com/shayyz-code/${p.slug}`
    : null

  lines.push(
    `INSERT INTO projects (id, slug, title, description, site_url, repo_url, media_key, position, published) VALUES (`,
    `  ${q(p.id)}, ${q(p.slug)}, ${q(p.title)}, ${q(p.description)},`,
    `  ${q(p.site)}, ${q(repoUrl)}, NULL, ${i}, 1`,
    `);`,
  )

  String(p.tags ?? "")
    .split(", ")
    .map((t) => t.trim())
    .filter(Boolean)
    .forEach((tag, pos) => {
      lines.push(
        `INSERT INTO project_tags (project_id, tag_id, position) ` +
          `SELECT ${q(p.id)}, id, ${pos} FROM tags WHERE name = ${q(tag)};`,
      )
    })
  lines.push("")
})

process.stdout.write(lines.join("\n") + "\n")

process.stderr.write(
  `${projects.length} projects, ${tagOrder.length} distinct tags, ` +
    `${projects.filter((p) => PUBLIC_REPOS.has(p.slug)).length} with repo_url\n`,
)
