// Copies project images out of Firebase Storage into R2 and records the
// resulting object key on each row.
//
// The download and the media_key assignment happen in ONE pass, so a row is
// never written pointing at a bucket that is about to be deleted. Objects are
// staged on disk first (.archive/media/) so a re-run does not re-download, and
// so the uploaded bytes can be inspected before they go anywhere.
//
// Usage:
//   node scripts/migrate-media.mjs            # download + emit SQL only
//   node scripts/migrate-media.mjs --upload   # ...and push to R2
//
// Then apply the emitted seeds/media.sql with `wrangler d1 execute`.

import { execFileSync } from "node:child_process"
import { mkdirSync, writeFileSync, existsSync, statSync } from "node:fs"
import { fileURLToPath } from "node:url"

const ROOT = fileURLToPath(new URL("..", import.meta.url))
const MEDIA_DIR = `${ROOT}.archive/media`
const BUCKET = "codewithshayy-media"
const upload = process.argv.includes("--upload")

const CONTENT_TYPES = {
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  gif: "image/gif",
  webp: "image/webp",
  avif: "image/avif",
  svg: "image/svg+xml",
}

const projects = JSON.parse(
  execFileSync("cat", [`${ROOT}.archive/projects.json`], { encoding: "utf8" }),
)

mkdirSync(MEDIA_DIR, { recursive: true })

const q = (v) => (v === null ? "NULL" : `'${String(v).replace(/'/g, "''")}'`)
const rows = []
const report = []

for (const p of projects) {
  if (!p.photo_url) {
    // dreamyfancies-pvs has no image. media_key stays NULL and the card
    // renders its titled placeholder.
    rows.push({ slug: p.slug, key: null })
    report.push({ slug: p.slug, status: "no image", bytes: 0 })
    continue
  }

  // Derive the extension from the storage path, not the URL tail — Firebase
  // URLs end in ?alt=media&token=...
  const storagePath = decodeURIComponent(
    (p.photo_url.split("/o/")[1] ?? "").split("?")[0],
  )
  const ext = (storagePath.match(/\.([a-z0-9]+)$/i)?.[1] ?? "png").toLowerCase()
  const key = `projects/${p.slug}.${ext}`
  const local = `${MEDIA_DIR}/${p.slug}.${ext}`

  if (!existsSync(local)) {
    const res = await fetch(p.photo_url)
    if (!res.ok) throw new Error(`${p.slug}: download failed ${res.status}`)
    const buf = Buffer.from(await res.arrayBuffer())
    if (buf.length === 0) throw new Error(`${p.slug}: downloaded 0 bytes`)
    writeFileSync(local, buf)
  }

  const bytes = statSync(local).size

  if (upload) {
    // --content-type is not optional: without it R2 stores no httpMetadata,
    // writeHttpMetadata() emits no Content-Type, and browsers have to sniff.
    execFileSync(
      "npx",
      [
        "wrangler", "r2", "object", "put", `${BUCKET}/${key}`,
        "--file", local,
        "--content-type", CONTENT_TYPES[ext] ?? "application/octet-stream",
        "--remote",
      ],
      { stdio: "pipe" },
    )
  }

  rows.push({ slug: p.slug, key })
  report.push({ slug: p.slug, status: upload ? "uploaded" : "staged", bytes, key })
}

const sql = [
  "-- Generated by scripts/migrate-media.mjs. Sets media_key on each project.",
  "",
  ...rows.map(
    (r) =>
      `UPDATE projects SET media_key = ${q(r.key)}, ` +
      `updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now') WHERE slug = ${q(r.slug)};`,
  ),
  "",
]
writeFileSync(`${ROOT}seeds/media.sql`, sql.join("\n"))

console.table(report)
console.log(`\nwrote seeds/media.sql (${rows.filter((r) => r.key).length} keys, ${rows.filter((r) => !r.key).length} null)`)
if (!upload) console.log("staged only — re-run with --upload to push to R2")
